meta_product_name: "Migrating Mango"
meta_title: "Migrating Mango - A fruity companion"
meta_description: "An app for people migrating to Switzerland"
meta_image: "app/assets/images/mangologo.png" # should exist in `app/assets/images/`
